apiVersion: apps/v1
kind: Deployment
metadata:
  name: nisit-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nisit-server
  template:
    metadata:
      labels:
        app: nisit-server
    spec:
      containers:
        - name: server
          image: nisit-server
          imagePullPolicy: Never
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "5000"
            - name: DATABASE_URL
              value: postgresql://postgres:password@postgres:5432/nisit?sslmode=disable
            - name: FRONTEND_URL
              value: https://nisit.k8s.dev
            - name: CORS_ORIGIN
              value: https://nisit.k8s.dev
            - name: GOOGLE_CALLBACK_URL
              value: https://nisit.k8s.dev/api/auth/google/callback
            - name: SESSION_COOKIE_SECURE
              value: "false"
            - name: SESSION_SECRET
              value: change-this-before-final-demo
            - name: GOOGLE_CLIENT_ID
              value: 479342713077-6mefnrab9mlk4mee2vbekepasfbs8e5p.apps.googleusercontent.com
            - name: GOOGLE_CLIENT_SECRET
              value: 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
            - name: MAX_FILE_SIZE
              value: "52428800"
            - name: CERT_THAI_FONT_PATH
              value: "/app/fonts/THSarabunNew.ttf"
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: nisit-server
spec:
  selector:
    app: nisit-server
  ports:
    - port: 5000
      targetPort: 5000
