apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nisit-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  ingressClassName: nginx
  rules:
    - host: nisit.k8s.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nisit-client
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: nisit-server
                port:
                  number: 5000
